config/routes.rb
Rails.application.routes.draw do
  resources :reservation_tables

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'selects#index'
  # Defines the root path route ("/")
  # root "articles#index"

  get 'reservation_tables/reserve'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation_table.rb
class ReservationTable < ApplicationRecord

  def self.reservations

    reservations = ReservationTable.all

    reservation_data = []
    reservations.each do |reservation|
      reservations_hash = {}
      reservations_hash.merge!(day: reservation.ReservationDate.strftime("%Y-%m-%d"), time: reservation.ReservationTime)
      reservation_data.push(reservations_hash)
    end
    reservation_data
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservation_tables_controller.rb
class ReservationTablesController < ApplicationController
  def index
    @reservation_tables = ReservationTable.all
    @reservation_table = ReservationTable.new
  end

  def reserve

  end

  def new
    @reservation_table = ReservationTable.new
    @day = params[:day]
  end

  def show
    @reservation_table = ReservationTable.find(params[:id])
  end

  def create
    ReservationTable.create(reservation_table_parameter)
    redirect_to reservation_tables_path
  end

  def destroy
    @reservation_table = ReservationTable.find(params[:id])
    @reservation_table.destroy
    redirect_to reservation_tables_path, notice:"deleted"
  end

  def edit
    @reservation_table = ReservationTable.find(params[:id])
  end

  def update
    @reservation_table = ReservationTable(params[:id])
    if @reservation_table.update(reservation_table_parameter)
      redirect_to reservation_tables_path, notice: "edited"
    else
      render 'edit'
    end
  end

  private

  def reservation_table_parameter
    params.require(:reservation_table).permit(:title, :context, :start_time)
  end
end

app/controllers/selects_controller.rb
class SelectsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservation_tables_helper.rb
module ReservationTablesHelper
    def times
        times = ["11:00",
                 "12:00",
                 "13:00",
                 "14:00",
                 "17:00",
                 "18:00",
                 "19:00",
                 "20:00",
                 "21:00",
                 "22:00"]
    end

    def tables
        tables = {
                  "テーブルA" => 0,
                  "テーブルB" => 1,
                  "テーブルC" => 2,
                  "テーブルD" => 3,
                  "テーブルE" => 4,
                  "テーブルF" => 5
                 }
    end

    def check_reservation(reservations, day, time)
      result = false
      reservations_count = reservations.count

      if reservations_count > 1
        reservations.each do |reservation|
          result = reservation[:day].eql?(day.strtime("%Y-%m-%d")) && reservation[:time].eql?(time)
          return result if result
        end
      elsif reservations_count == 1
        result = reservation[:day].eql?(day.strftime("%Y-%m-%d")) && reservations[0][:time].eql?(time)
        return result if result
      end
      return result
    end
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Reservation
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = yield

app/views/reservation_tables/edit.html.slim
= form_with(model: @reservation_table, local: true) do |form|

  .title
    .form-tag title
    = form.text_field(:title)

  .content
    .form-tag content
    = form.text_field(:content)

    .time
    .form-tag time
    = form.datetime_select(:start_time)

    .submit
      = form.submit

app/views/reservation_tables/index.html.slim
p #notice = notice

.toppage
  h1.top 予約表
br

.col-md-8
  = month_calendar events: @reservation_tables do | date, reservation_tables|
    = date.day

    - reservation_tables.each do |reservation_table|
      = link_to reservation_table.title, reservation_table

app/views/reservation_tables/new.html.slim
h1 予約表
- reservations = ReservationTable.reservations
br
br

=@day
table.table_new 
  tr.tr_new
    th.th_new#time 時間
    - tables.each_key do |table|
      th.th_new#table = table
  - times.each do |time|
    tr.tr_new
      td.td_new#time= time
      - tables.each do |table|
        - if check_reservation(reservations, @day, time)
          = "満席"
        else
          td.td_new#pointer= link_to '空席', new_reservation_table_path(@day)
         

app/views/reservation_tables/reserve.html.slim
h1 reserve

app/views/reservation_tables/show.html.slim
p #notice = notice 
  .show
p
  strong title
  = @reservation_table.title

p
  strong content
  = @reservation_table.content

p
  strong date
  = @reservation_table.start_time.strftime("%m-%d")

= link_to 'edit', edit_reservation_table_path(@reservation_table), class:'btn btn-primary'
= link_to 'delete', @reservation_table, method: :delete, data: { confirm: 'really?' },class:'btn btn-primary'
= link_to 'back', reservation_tables_path,class:'btn btn-primary'

app/views/selects/index.html.slim
h1 レストラン業務管理システム
.container1
  
  button.button1 type="button"  onclick ="location.href='reservation_tables'" 予約管理
  button.button1 type="button" 顧客管理
  button.button1 type="button" 売上管理
  button.button1 type="button" シフト管理

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '次'), calendar.url_for_next_view %>
    <% reservations = ReservationTable.reservations %> 
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
                <%= link_to '空席', new_reservation_table_path(day: day) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>